name: Create Release from version.txt

on:
  push:
    branches:
      - main

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Read version from file
        id: read_version
        run: |
          VERSION=$(cat update/version.txt)
          echo "VERSION=$VERSION"
          echo "version=$VERSION" >> $GITHUB_ENV

      - name: Create Git Tag
        run: |
          git config --global user.name "DiumStream-tech"
          git config --global user.email "diumstream@gmail.com"
          git tag -a "$VERSION" -m "Release $VERSION"
          git push origin "$VERSION"

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: "Release ${{ env.VERSION }}"
          body: "Automated release for version ${{ env.VERSION }}"
          draft: false
          prerelease: false
