name: Create Tag and Release

on:
  push:
    branches:
      - main

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Vérifier le dépôt
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Lire et valider la version depuis le fichier distant version.txt
      - name: Read version from remote file
        id: read_version
        run: |
          # Télécharger le contenu brut du fichier version.txt depuis GitHub
          VERSION=$(curl -s https://raw.githubusercontent.com/DiumStream-tech/DiumStream-Panel/main/update/version.txt | tr -d '[:space:]')
          
          # Vérifier si la version est vide ou invalide
          if [[ -z "$VERSION" ]]; then
            echo "Erreur : La version est vide ou invalide."
            exit 1
          fi

          # Vérifier si la version respecte le format SemVer (exemple : v1.0.0)
          if ! [[ "$VERSION" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Erreur : La version doit être au format SemVer, par exemple v1.0.0."
            exit 1
          fi

          echo "VERSION=$VERSION"
          echo "version=$VERSION" >> $GITHUB_ENV

      # Étape 3 : Configurer Git pour créer un tag
      - name: Configure Git
        run: |
          git config --global user.name "DiumStream-tech"
          git config --global user.email "actions@github.com"

      # Étape 4 : Créer un tag avec la version récupérée
      - name: Create Git Tag
        run: |
          git tag -a "$VERSION" -m "Release $VERSION"
          git push origin "$VERSION"

      # Étape 5 : Créer une release GitHub associée au tag créé
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: "Release ${{ env.VERSION }}"
          body: "Automated release for version ${{ env.VERSION }}"
          draft: false
          prerelease: false
